version: '3'
services:
  master1:
    image: mysql:5.7
    env_file:
      - ./master1/master1.env
    container_name: "master1"
    restart: "no"
    ports:
      - 4406:3306
    volumes:
      - ./master1/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./master1/data:/var/lib/mysql
    networks:
      - overlay

  master2:
    image: mysql:5.7
    env_file:
      - ./master2/master2.env
    container_name: "master2"
    restart: "no"
    ports:
      - 5506:3306
    #depends_on:
    #  - master1
    volumes:
      - ./master2/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./master2/data:/var/lib/mysql
    networks:
      - overlay

networks:
  overlay:
